data "aws_iam_policy_document" "eso_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]    #Allow pod to call sts service(eso pod will use oidc token to assume iam role)
    effect  = "Allow"

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:sub"  # Read sub(identity) claim from incoming oidc token
      values   = ["system:serviceaccount:kube-system:external-secrets"]
        # check the incoming tokens sub fiels. it its value value exactly matches system:serviceaccount:kube-system:external-secrets, allow role assumption.
        # [here exactly matches both varaible(Actual value from oidc token) == values(Expected/allowed value)]
    }

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:aud"
      values   = ["sts.amazonaws.com"]
         # check token audience(aud) field . Allow only if audience equals  to sts.amazonaws.com
    }

    principals {
      identifiers = [var.oidc_provider_arn]   # specifies trusted eks oidc provider
      type        = "Federated"         # trust external idp   (trust tokens generated by this eks cluster)
    }
  }
}

resource "aws_iam_role" "eso_role" {
  name               = "${var.project}-${var.env}-eso-role"
  assume_role_policy = data.aws_iam_policy_document.eso_assume_role.json  # This role can be assumed ONLY by allowed ESO pod

  tags = {
    Name    = "${var.project}-${var.env}-eso-role"
    Env     = var.env
    Project = var.project   # AWS identity for ESO pod(Trust Policy)
  }
}

resource "aws_iam_policy" "eso_secrets_policy" {     # what AWS action ESO pod can perform(permission policy)
  name        = "${var.project}-${var.env}-eso-secrets-policy"
  description = "Allow External Secrets Operator to read pharma secrets from AWS Secrets Manager"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret"
        ]
        Resource = "arn:aws:secretsmanager:*:${var.aws_account_id}:secret:/pharma/*" # Restrict accessible secrets(secret managers has number of secret obj)
      }                                                    # ESO pod can access within in pharma secrets(read pharma secrets from decret manager)
    ]
  })
}

resource "aws_iam_role_policy_attachment" "eso_secrets_attachment" {
  role       = aws_iam_role.eso_role.name
  policy_arn = aws_iam_policy.eso_secrets_policy.arn
}
#Work Flow  for ESO :   ESO pod starts --> pod(svc account: external-secrets) --> Eks generates OIDC token  --> AWS SDK inside ESO pod reads (oidc token, iam ro])
#le ARN) --> SDK Will make can api call to aes sts serviced(here STS Validates c oidc provider, sub, aud) --> if allow, STS issues temprorary aws credentials
# ----> ESO uses those credentials to call secret manager APIS --> ESO fethes secrets ----> ESO pos sync to k8s secret obj --> App pods can consume k8s secrets.


# ArgoCD IRSA Role
data "aws_iam_policy_document" "argocd_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:sub"
      values   = ["system:serviceaccount:argocd:argocd-application-controller"]
    }

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:aud"
      values   = ["sts.amazonaws.com"]
    }

    principals {
      identifiers = [var.oidc_provider_arn]
      type        = "Federated"
    }
  }
}

resource "aws_iam_role" "argocd_role" {
  name               = "${var.project}-${var.env}-argocd-role"
  assume_role_policy = data.aws_iam_policy_document.argocd_assume_role.json

  tags = {
    Name    = "${var.project}-${var.env}-argocd-role"
    Env     = var.env
    Project = var.project
  }
}

# GitLab Runner IRSA Role
data "aws_iam_policy_document" "gitlab_runner_assume_role" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    effect  = "Allow"

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:sub"
      values   = ["system:serviceaccount:gitlab-runner:gitlab-runner"]
    }

    condition {
      test     = "StringEquals"
      variable = "${replace(var.oidc_provider_url, "https://", "")}:aud"
      values   = ["sts.amazonaws.com"]
    }

    principals {
      identifiers = [var.oidc_provider_arn]
      type        = "Federated"
    }
  }
}

resource "aws_iam_role" "gitlab_runner_role" {
  name               = "${var.project}-${var.env}-gitlab-runner-role"
  assume_role_policy = data.aws_iam_policy_document.gitlab_runner_assume_role.json

  tags = {
    Name    = "${var.project}-${var.env}-gitlab-runner-role"
    Env     = var.env
    Project = var.project
  }
}

resource "aws_iam_policy" "gitlab_runner_policy" {
  name        = "${var.project}-${var.env}-gitlab-runner-policy"
  description = "Allow GitLab Runner to push to ECR and describe EKS"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ecr:GetAuthorizationToken",
          "ecr:BatchCheckLayerAvailability",
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage",
          "ecr:PutImage",
          "ecr:InitiateLayerUpload",
          "ecr:UploadLayerPart",
          "ecr:CompleteLayerUpload",
          "ecr:DescribeRepositories",
          "ecr:ListImages",
          "ecr:DescribeImages"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "eks:DescribeCluster",
          "eks:ListClusters"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "gitlab_runner_policy_attachment" {
  role       = aws_iam_role.gitlab_runner_role.name
  policy_arn = aws_iam_policy.gitlab_runner_policy.arn
}
